matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
language: node_js
node_js:
<<<<<<< HEAD
=======
  - 9.2.0
>>>>>>> 3bf136c385a9545b562cf8ee696105f988ccac60
  - 13.0.0
  - lts/*
before_install:
  - npm i -g npm@latest
script:
  - npm run coverage
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
git:
  depth: false
cache: npm
