matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
language: node_js
node_js:
  - 13.0.0
  - lts/*
before_install:
  - npm i -g codecov
  - npm i -g npm@latest
script:
  - npm run coverage
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
git:
  depth: false
cache: npm
